### ISSUE TITLE
Add schema support for "ERRORS"

### ISSUE THREAD

**Issue by avdv** [sun-opsys/api-doc#16]
Currently, it is not possible to specify the schema for error responses.

According to the Swagger 2.0 spec,  "If this field does not exist, it means no content is returned as part of the response.".

Since the Swagger spec unifies all possible responses (whether being success or error) in a single object, it might be a good idea for the Api-Doc, too?

**Comment by kmatheussen** [comment]
Sounds like a good idea, but I guess the api-doc syntax needs to be extended?

How about something like this:

```
RESULT
    User
```

is the same as

```
RESULT
    200 -> User
```

And you can also write:

```
RESULT
   200 -> User
   400 -> ErrorUser1
   401 -> ErrorUser2

ERRORS
   400 User not found
   400 Syntax Error
```

**Comment by kmatheussen** [comment]
Or write this:

```
RESULT
   200 -> User
   400 -> ErrorUser1 <- User not found
   401 -> ErrorUser2 <- Computer crashed
```

which is the same as this:

```
RESULT
   200 -> User
   400 -> ErrorUser1
   401 -> ErrorUser2

ERRORS
   400 User not found
   401 Computer crashed
```

**Comment by kmatheussen** [comment]
Better use colon instead of ->:

```
RESULT
   200: User
   400: ErrorUser1
   401: ErrorUser2

ERRORS
   400 User not found
   401 Computer crashed
```

**Comment by avdv** [comment]
> Better use colon instead of ->:

Yes, that would be my favorite, too. With `<-` used for adding a description, similar to the PARAMETERS.

**Comment by kmatheussen** [comment]
Fixed
