### ISSUE TITLE
Sample example for post request

### ISSUE THREAD

**Issue by maninder-singh** [sun-opsys/api-doc#18]
Hi,
I have a post request like : localhost:9000/users
with request body data to be posted as { "id" : 1,"firstName" : "abc" }.
How could we implement in @ApiDoc.

**Comment by kmatheussen** [comment]
Hi, the "POST /user2admin/api/v1/guser" end point in the included example file pretty much does exactly this:
https://github.com/sun-opsys/api-doc/blob/master/app/controllers/UserController.scala#L87

In the README.md file under "QUICK START" there are instructions on how you run this example.

**Comment by maninder-singh** [comment]
Thanks for reply.
