### ISSUE TITLE
jar for the lib?

### ISSUE THREAD

**Issue by bsadeh** [sun-opsys/api-doc#5]
is this lib packaged and hosted anywhere so we can add it as a dependency?

**Comment by aloiscochard** [comment]
:+1:

**Comment by mirkof** [comment]
++

**Comment by kmatheussen** [comment]
I don't know how to do that. Is there any non-bloated recipe anywhere on how to package and host jar files?

**Comment by kmatheussen** [comment]
This seems to work now:
```
resolvers += "jitpack" at "https://jitpack.io"
libraryDependencies += "com.github.sun-opsys" % "api-doc" % "0.9.9"
```

I've also added a quick and dirty recipe to the README file on how to include api-doc in an existing project (without copying all files manually).

Now the project needs a new name....
